version: '3.9'

networks:
  network_iot:
    external:
      name: iot-net

services:
  www:
    container_name: tharsis
    build: .
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=tharsis.pe, www.tharsis.pe
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=tharsis.pe, www.tharsis.pe
      - LETSENCRYPT_EMAIL=jcanahuirev@gmail.com
    networks:
      - network_iot